package hr.ispit.drzave.config;
import hr.ispit.drzave.security.JwtFilter; import org.springframework.context.annotation.*; import org.springframework.security.authentication.*; import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.config.http.SessionCreationPolicy; import org.springframework.security.core.userdetails.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.security.provisioning.InMemoryUserDetailsManager; import org.springframework.security.web.SecurityFilterChain; import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
@Configuration @EnableMethodSecurity public class SecurityConfig {
 @Bean PasswordEncoder encoder(){return new BCryptPasswordEncoder();}
 @Bean UserDetailsService users(PasswordEncoder e){return new InMemoryUserDetailsManager(User.withUsername("admin").password(e.encode("admin123")).roles("ADMIN","USER").build(),User.withUsername("user").password(e.encode("user123")).roles("USER").build());}
 @Bean AuthenticationManager manager(AuthenticationConfiguration c)throws Exception{return c.getAuthenticationManager();}
 @Bean SecurityFilterChain chain(HttpSecurity h,JwtFilter f)throws Exception{return h.csrf(c->c.disable()).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/auth/**","/h2-console/**").permitAll().requestMatchers(org.springframework.http.HttpMethod.GET,"/api/drzave/**").hasAnyRole("USER","ADMIN").requestMatchers("/api/drzave/**").hasRole("ADMIN").anyRequest().authenticated()).headers(x->x.frameOptions(y->y.sameOrigin())).addFilterBefore(f,UsernamePasswordAuthenticationFilter.class).build();}
}

