INSERT INTO KONTINENT (NAZIV) VALUES('Afrika');
INSERT INTO KONTINENT (NAZIV) VALUES('Azija');
INSERT INTO KONTINENT (NAZIV) VALUES('Evropa');
INSERT INTO KONTINENT (NAZIV) VALUES('Sjeverna Amerika');
INSERT INTO KONTINENT (NAZIV) VALUES('Australija');
INSERT INTO KONTINENT (NAZIV) VALUES('Antarktika');
INSERT INTO KONTINENT (NAZIV) VALUES('Južna Amerika');

INSERT INTO DRZAVA (NAZIV, BROJ_STANOVNIKA, KONTINENT)
        VALUES('Hrvatska', 4000000, 3);
INSERT INTO DRZAVA (NAZIV, BROJ_STANOVNIKA, KONTINENT)
        VALUES('Sjedinjene Američke Države', 335000000, 4);